/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 924bXs3onQpKzyMi97MqJv

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantseLvi9Mw6KdrB } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ELvi9MW6KdrB/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantseLvi9Mw6KdrB
});
