/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 924bXs3onQpKzyMi97MqJv
// Component: oczCFi_qY_EP

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 924bXs3onQpKzyMi97MqJv/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 924bXs3onQpKzyMi97MqJv/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 924bXs3onQpKzyMi97MqJv/projectcss
import sty from "./PlasmicListItemWithHeader.module.css"; // plasmic-import: oczCFi_qY_EP/css

createPlasmicElementProxy;

export type PlasmicListItemWithHeader__VariantMembers = {};
export type PlasmicListItemWithHeader__VariantsArgs = {};
type VariantPropType = keyof PlasmicListItemWithHeader__VariantsArgs;
export const PlasmicListItemWithHeader__VariantProps =
  new Array<VariantPropType>();

export type PlasmicListItemWithHeader__ArgsType = {
  columnName?: string;
  itemDescription?: string;
};
type ArgPropType = keyof PlasmicListItemWithHeader__ArgsType;
export const PlasmicListItemWithHeader__ArgProps = new Array<ArgPropType>(
  "columnName",
  "itemDescription"
);

export type PlasmicListItemWithHeader__OverridesType = {
  root?: Flex__<"div">;
  headerPartner?: Flex__<"div">;
  partner?: Flex__<"div">;
};

export interface DefaultListItemWithHeaderProps {
  columnName?: string;
  itemDescription?: string;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicListItemWithHeader__RenderFunc(props: {
  variants: PlasmicListItemWithHeader__VariantsArgs;
  args: PlasmicListItemWithHeader__ArgsType;
  overrides: PlasmicListItemWithHeader__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          columnName: "columnName",
          itemDescription: "itemDescription"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const currentUser = useCurrentUser?.() || {};

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"headerPartner"}
        data-plasmic-override={overrides.headerPartner}
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.headerPartner
        )}
      >
        <React.Fragment>
          {(() => {
            try {
              return $props.columnName;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return "Partner";
              }
              throw e;
            }
          })()}
        </React.Fragment>
      </div>
      <div
        data-plasmic-name={"partner"}
        data-plasmic-override={overrides.partner}
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.partner
        )}
      >
        <React.Fragment>
          {(() => {
            try {
              return $props.itemDescription;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return "";
              }
              throw e;
            }
          })()}
        </React.Fragment>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "headerPartner", "partner"],
  headerPartner: ["headerPartner"],
  partner: ["partner"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  headerPartner: "div";
  partner: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicListItemWithHeader__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicListItemWithHeader__VariantsArgs;
    args?: PlasmicListItemWithHeader__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicListItemWithHeader__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicListItemWithHeader__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicListItemWithHeader__ArgProps,
          internalVariantPropNames: PlasmicListItemWithHeader__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicListItemWithHeader__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicListItemWithHeader";
  } else {
    func.displayName = `PlasmicListItemWithHeader.${nodeName}`;
  }
  return func;
}

export const PlasmicListItemWithHeader = Object.assign(
  // Top-level PlasmicListItemWithHeader renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerPartner: makeNodeComponent("headerPartner"),
    partner: makeNodeComponent("partner"),

    // Metadata about props expected for PlasmicListItemWithHeader
    internalVariantProps: PlasmicListItemWithHeader__VariantProps,
    internalArgProps: PlasmicListItemWithHeader__ArgProps
  }
);

export default PlasmicListItemWithHeader;
/* prettier-ignore-end */
