/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 924bXs3onQpKzyMi97MqJv
// Component: cG-RUM6LDbn9

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import NavMenuItem from "../../NavMenuItem"; // plasmic-import: 9g4QnerbojGg/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 924bXs3onQpKzyMi97MqJv/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 924bXs3onQpKzyMi97MqJv/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 924bXs3onQpKzyMi97MqJv/projectcss
import sty from "./PlasmicSideBarNavigation.module.css"; // plasmic-import: cG-RUM6LDbn9/css

import CartLargeSvgrepoComSvgIcon from "./icons/PlasmicIcon__CartLargeSvgrepoComSvg"; // plasmic-import: ObuKbDV7tVS_/icon
import ChatRoundMoneySvgrepoComSvgIcon from "./icons/PlasmicIcon__ChatRoundMoneySvgrepoComSvg"; // plasmic-import: q3kz7cfSHgMp/icon
import ClipboardCheckSvgrepoComSvgIcon from "./icons/PlasmicIcon__ClipboardCheckSvgrepoComSvg"; // plasmic-import: gOv0XEqKHtlU/icon
import Book2SvgrepoComSvgIcon from "./icons/PlasmicIcon__Book2SvgrepoComSvg"; // plasmic-import: D6u7WlVb5HN2/icon
import BoxMinimalisticSvgrepoComSvgIcon from "./icons/PlasmicIcon__BoxMinimalisticSvgrepoComSvg"; // plasmic-import: wY4ekpxh-r7H/icon
import LibrarySvgrepoComSvgIcon from "./icons/PlasmicIcon__LibrarySvgrepoComSvg"; // plasmic-import: ZN81dtPMMDRa/icon
import HomeSmileAngleSvgrepoComSvgIcon from "./icons/PlasmicIcon__HomeSmileAngleSvgrepoComSvg"; // plasmic-import: -i9Ro8K7LFdI/icon
import UsersGroupRoundedSvgrepoComSvgIcon from "./icons/PlasmicIcon__UsersGroupRoundedSvgrepoComSvg"; // plasmic-import: 67OKyp4YDgLN/icon

createPlasmicElementProxy;

export type PlasmicSideBarNavigation__VariantMembers = {};
export type PlasmicSideBarNavigation__VariantsArgs = {};
type VariantPropType = keyof PlasmicSideBarNavigation__VariantsArgs;
export const PlasmicSideBarNavigation__VariantProps =
  new Array<VariantPropType>();

export type PlasmicSideBarNavigation__ArgsType = {
  currentPage?: string;
  onCurrentPageChange2?: (val: string) => void;
};
type ArgPropType = keyof PlasmicSideBarNavigation__ArgsType;
export const PlasmicSideBarNavigation__ArgProps = new Array<ArgPropType>(
  "currentPage",
  "onCurrentPageChange2"
);

export type PlasmicSideBarNavigation__OverridesType = {
  root?: Flex__<"div">;
  freeBox?: Flex__<"div">;
  sideBar?: Flex__<"div">;
  purchasing?: Flex__<"div">;
  navMenuItem?: Flex__<typeof NavMenuItem>;
  sectionPlanning2?: Flex__<"div">;
  sectionTitlePlanning2?: Flex__<"div">;
  navMenuItem2?: Flex__<typeof NavMenuItem>;
  navMenuItem3?: Flex__<typeof NavMenuItem>;
  navMenuItem4?: Flex__<typeof NavMenuItem>;
  sectionResources?: Flex__<"div">;
  sectionTitleResources?: Flex__<"div">;
  navMenuItem5?: Flex__<typeof NavMenuItem>;
  navMenuItem6?: Flex__<typeof NavMenuItem>;
  navMenuItem7?: Flex__<typeof NavMenuItem>;
  navMenuItem8?: Flex__<typeof NavMenuItem>;
  navMenuItem9?: Flex__<typeof NavMenuItem>;
  navMenuItem10?: Flex__<typeof NavMenuItem>;
};

export interface DefaultSideBarNavigationProps {
  currentPage?: string;
  onCurrentPageChange2?: (val: string) => void;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSideBarNavigation__RenderFunc(props: {
  variants: PlasmicSideBarNavigation__VariantsArgs;
  args: PlasmicSideBarNavigation__ArgsType;
  overrides: PlasmicSideBarNavigation__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "currentPage",
        type: "writable",
        variableType: "text",

        valueProp: "currentPage",
        onChangeProp: "onCurrentPageChange2"
      },
      {
        path: "menuIconSize",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 20
      },
      {
        path: "navMenuItem.highlightActive",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "navMenuItem2.highlightActive",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "navMenuItem3.highlightActive",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "navMenuItem4.highlightActive",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "navMenuItem5.highlightActive",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "navMenuItem6.highlightActive",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "navMenuItem7.highlightActive",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "navMenuItem8.highlightActive",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "navMenuItem9.highlightActive",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "navMenuItem10.highlightActive",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const [isRootHover, triggerRootHoverProps] = useTrigger("useHover", {});
  const triggers = {
    hover_root: isRootHover
  };

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
      data-plasmic-trigger-props={[triggerRootHoverProps]}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        <div
          data-plasmic-name={"sideBar"}
          data-plasmic-override={overrides.sideBar}
          className={classNames(projectcss.all, sty.sideBar)}
        >
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__st6Tm)}
            displayHeight={"40px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"none"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"100%"}
            loading={"lazy"}
            src={{
              src: "/plasmic/dev_po_jc_playground/images/bespokeHouseIconNavyIconPng.png",
              fullWidth: 3334,
              fullHeight: 3334,
              aspectRatio: undefined
            }}
          />

          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__dlhfV)}
            displayHeight={"32px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"none"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: "/plasmic/dev_po_jc_playground/images/blinkPng.png",
              fullWidth: 1993,
              fullHeight: 661,
              aspectRatio: undefined
            }}
          />

          <div
            data-plasmic-name={"purchasing"}
            data-plasmic-override={overrides.purchasing}
            className={classNames(projectcss.all, sty.purchasing)}
          >
            <NavMenuItem
              data-plasmic-name={"navMenuItem"}
              data-plasmic-override={overrides.navMenuItem}
              className={classNames("__wab_instance", sty.navMenuItem)}
              expanded={triggers.hover_root ? true : false}
              highlightActive={generateStateValueProp($state, [
                "navMenuItem",
                "highlightActive"
              ])}
              itemBorderOn={
                triggers.hover_root
                  ? undefined
                  : (() => {
                      try {
                        return $state.navMenuItem.highlightActive;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return [];
                        }
                        throw e;
                      }
                    })()
              }
              menuActiveBorder={
                triggers.hover_root
                  ? false
                  : (() => {
                      try {
                        return $state.currentPage === "/purchase-orders-main";
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return false;
                        }
                        throw e;
                      }
                    })()
              }
              menuItemName={triggers.hover_root ? "Purchase Orders" : undefined}
              navLink={
                triggers.hover_root ? `/purchase-orders-main` : `/job-costing`
              }
              onHighlightActiveChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, [
                  "navMenuItem",
                  "highlightActive"
                ]).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
            >
              <PlasmicIcon__
                PlasmicIconType={
                  triggers.hover_root
                    ? CartLargeSvgrepoComSvgIcon
                    : CartLargeSvgrepoComSvgIcon
                }
                className={classNames(projectcss.all, sty.svg__s36LR)}
                role={"img"}
              />
            </NavMenuItem>
          </div>
          <div
            data-plasmic-name={"sectionPlanning2"}
            data-plasmic-override={overrides.sectionPlanning2}
            className={classNames(projectcss.all, sty.sectionPlanning2)}
          >
            <div
              data-plasmic-name={"sectionTitlePlanning2"}
              data-plasmic-override={overrides.sectionTitlePlanning2}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.sectionTitlePlanning2
              )}
            >
              {"Planning"}
            </div>
            <NavMenuItem
              data-plasmic-name={"navMenuItem2"}
              data-plasmic-override={overrides.navMenuItem2}
              expanded={triggers.hover_root ? true : false}
              highlightActive={generateStateValueProp($state, [
                "navMenuItem2",
                "highlightActive"
              ])}
              itemBorderOn={triggers.hover_root ? undefined : undefined}
              menuActiveBorder={false}
              navLink={`/job-costing`}
              onHighlightActiveChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, [
                  "navMenuItem2",
                  "highlightActive"
                ]).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
            >
              <PlasmicIcon__
                PlasmicIconType={
                  triggers.hover_root
                    ? ChatRoundMoneySvgrepoComSvgIcon
                    : ChatRoundMoneySvgrepoComSvgIcon
                }
                className={classNames(projectcss.all, sty.svg__f51Ki)}
                role={"img"}
              />
            </NavMenuItem>
            <NavMenuItem
              data-plasmic-name={"navMenuItem3"}
              data-plasmic-override={overrides.navMenuItem3}
              className={classNames("__wab_instance", sty.navMenuItem3)}
              expanded={triggers.hover_root ? true : false}
              highlightActive={generateStateValueProp($state, [
                "navMenuItem3",
                "highlightActive"
              ])}
              menuItemName={triggers.hover_root ? "Takeoffs" : "Takeoffs"}
              navLink={triggers.hover_root ? `/` : `/`}
              onHighlightActiveChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, [
                  "navMenuItem3",
                  "highlightActive"
                ]).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
            >
              <ClipboardCheckSvgrepoComSvgIcon
                className={classNames(projectcss.all, sty.svg__uDnQc)}
                role={"img"}
              />
            </NavMenuItem>
            <NavMenuItem
              data-plasmic-name={"navMenuItem4"}
              data-plasmic-override={overrides.navMenuItem4}
              className={classNames("__wab_instance", sty.navMenuItem4)}
              expanded={triggers.hover_root ? true : false}
              highlightActive={generateStateValueProp($state, [
                "navMenuItem4",
                "highlightActive"
              ])}
              menuItemName={triggers.hover_root ? "Price Book" : "Price Book"}
              navLink={triggers.hover_root ? `/` : `/`}
              onHighlightActiveChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, [
                  "navMenuItem4",
                  "highlightActive"
                ]).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
            >
              <Book2SvgrepoComSvgIcon
                className={classNames(projectcss.all, sty.svg__pYfn4)}
                role={"img"}
              />
            </NavMenuItem>
          </div>
          <div
            data-plasmic-name={"sectionResources"}
            data-plasmic-override={overrides.sectionResources}
            className={classNames(projectcss.all, sty.sectionResources)}
          >
            <div
              data-plasmic-name={"sectionTitleResources"}
              data-plasmic-override={overrides.sectionTitleResources}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.sectionTitleResources
              )}
            >
              {"Resources"}
            </div>
            <NavMenuItem
              data-plasmic-name={"navMenuItem5"}
              data-plasmic-override={overrides.navMenuItem5}
              className={classNames("__wab_instance", sty.navMenuItem5)}
              expanded={triggers.hover_root ? true : false}
              highlightActive={generateStateValueProp($state, [
                "navMenuItem5",
                "highlightActive"
              ])}
              menuItemName={triggers.hover_root ? "Kits" : "Kits"}
              navLink={triggers.hover_root ? `/` : `/`}
              onHighlightActiveChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, [
                  "navMenuItem5",
                  "highlightActive"
                ]).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
            >
              <BoxMinimalisticSvgrepoComSvgIcon
                className={classNames(projectcss.all, sty.svg___7DDKu)}
                role={"img"}
              />
            </NavMenuItem>
            <NavMenuItem
              data-plasmic-name={"navMenuItem6"}
              data-plasmic-override={overrides.navMenuItem6}
              className={classNames("__wab_instance", sty.navMenuItem6)}
              expanded={triggers.hover_root ? true : false}
              highlightActive={generateStateValueProp($state, [
                "navMenuItem6",
                "highlightActive"
              ])}
              menuItemName={triggers.hover_root ? "Catalog" : "Catalog"}
              navLink={triggers.hover_root ? `/` : `/`}
              onHighlightActiveChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, [
                  "navMenuItem6",
                  "highlightActive"
                ]).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
            >
              <LibrarySvgrepoComSvgIcon
                className={classNames(projectcss.all, sty.svg___3UJlK)}
                role={"img"}
              />
            </NavMenuItem>
            <NavMenuItem
              data-plasmic-name={"navMenuItem7"}
              data-plasmic-override={overrides.navMenuItem7}
              className={classNames("__wab_instance", sty.navMenuItem7)}
              expanded={triggers.hover_root ? true : false}
              highlightActive={generateStateValueProp($state, [
                "navMenuItem7",
                "highlightActive"
              ])}
              menuItemName={triggers.hover_root ? "Jobs" : "Jobs"}
              navLink={triggers.hover_root ? `/` : `/`}
              onHighlightActiveChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, [
                  "navMenuItem7",
                  "highlightActive"
                ]).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
            >
              <ClipboardCheckSvgrepoComSvgIcon
                className={classNames(projectcss.all, sty.svg__tPh6E)}
                role={"img"}
              />
            </NavMenuItem>
            <NavMenuItem
              data-plasmic-name={"navMenuItem8"}
              data-plasmic-override={overrides.navMenuItem8}
              className={classNames("__wab_instance", sty.navMenuItem8)}
              expanded={triggers.hover_root ? true : false}
              highlightActive={generateStateValueProp($state, [
                "navMenuItem8",
                "highlightActive"
              ])}
              menuItemName={triggers.hover_root ? "Models" : "Models"}
              navLink={triggers.hover_root ? `/` : `/`}
              onHighlightActiveChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, [
                  "navMenuItem8",
                  "highlightActive"
                ]).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
            >
              <HomeSmileAngleSvgrepoComSvgIcon
                className={classNames(projectcss.all, sty.svg__etmGf)}
                role={"img"}
              />
            </NavMenuItem>
            <NavMenuItem
              data-plasmic-name={"navMenuItem9"}
              data-plasmic-override={overrides.navMenuItem9}
              className={classNames("__wab_instance", sty.navMenuItem9)}
              expanded={triggers.hover_root ? true : false}
              highlightActive={generateStateValueProp($state, [
                "navMenuItem9",
                "highlightActive"
              ])}
              menuItemName={triggers.hover_root ? "Partners" : "Partners"}
              navLink={triggers.hover_root ? `/` : `/`}
              onHighlightActiveChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, [
                  "navMenuItem9",
                  "highlightActive"
                ]).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
            >
              <UsersGroupRoundedSvgrepoComSvgIcon
                className={classNames(projectcss.all, sty.svg__t1Ye)}
                role={"img"}
              />
            </NavMenuItem>
            <NavMenuItem
              data-plasmic-name={"navMenuItem10"}
              data-plasmic-override={overrides.navMenuItem10}
              className={classNames("__wab_instance", sty.navMenuItem10)}
              expanded={triggers.hover_root ? true : true}
              highlightActive={generateStateValueProp($state, [
                "navMenuItem10",
                "highlightActive"
              ])}
              menuItemName={triggers.hover_root ? "Price Book" : "Price Book"}
              navLink={triggers.hover_root ? `/` : `/`}
              onHighlightActiveChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, [
                  "navMenuItem10",
                  "highlightActive"
                ]).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
            />
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "freeBox",
    "sideBar",
    "purchasing",
    "navMenuItem",
    "sectionPlanning2",
    "sectionTitlePlanning2",
    "navMenuItem2",
    "navMenuItem3",
    "navMenuItem4",
    "sectionResources",
    "sectionTitleResources",
    "navMenuItem5",
    "navMenuItem6",
    "navMenuItem7",
    "navMenuItem8",
    "navMenuItem9",
    "navMenuItem10"
  ],
  freeBox: [
    "freeBox",
    "sideBar",
    "purchasing",
    "navMenuItem",
    "sectionPlanning2",
    "sectionTitlePlanning2",
    "navMenuItem2",
    "navMenuItem3",
    "navMenuItem4",
    "sectionResources",
    "sectionTitleResources",
    "navMenuItem5",
    "navMenuItem6",
    "navMenuItem7",
    "navMenuItem8",
    "navMenuItem9",
    "navMenuItem10"
  ],
  sideBar: [
    "sideBar",
    "purchasing",
    "navMenuItem",
    "sectionPlanning2",
    "sectionTitlePlanning2",
    "navMenuItem2",
    "navMenuItem3",
    "navMenuItem4",
    "sectionResources",
    "sectionTitleResources",
    "navMenuItem5",
    "navMenuItem6",
    "navMenuItem7",
    "navMenuItem8",
    "navMenuItem9",
    "navMenuItem10"
  ],
  purchasing: ["purchasing", "navMenuItem"],
  navMenuItem: ["navMenuItem"],
  sectionPlanning2: [
    "sectionPlanning2",
    "sectionTitlePlanning2",
    "navMenuItem2",
    "navMenuItem3",
    "navMenuItem4"
  ],
  sectionTitlePlanning2: ["sectionTitlePlanning2"],
  navMenuItem2: ["navMenuItem2"],
  navMenuItem3: ["navMenuItem3"],
  navMenuItem4: ["navMenuItem4"],
  sectionResources: [
    "sectionResources",
    "sectionTitleResources",
    "navMenuItem5",
    "navMenuItem6",
    "navMenuItem7",
    "navMenuItem8",
    "navMenuItem9",
    "navMenuItem10"
  ],
  sectionTitleResources: ["sectionTitleResources"],
  navMenuItem5: ["navMenuItem5"],
  navMenuItem6: ["navMenuItem6"],
  navMenuItem7: ["navMenuItem7"],
  navMenuItem8: ["navMenuItem8"],
  navMenuItem9: ["navMenuItem9"],
  navMenuItem10: ["navMenuItem10"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
  sideBar: "div";
  purchasing: "div";
  navMenuItem: typeof NavMenuItem;
  sectionPlanning2: "div";
  sectionTitlePlanning2: "div";
  navMenuItem2: typeof NavMenuItem;
  navMenuItem3: typeof NavMenuItem;
  navMenuItem4: typeof NavMenuItem;
  sectionResources: "div";
  sectionTitleResources: "div";
  navMenuItem5: typeof NavMenuItem;
  navMenuItem6: typeof NavMenuItem;
  navMenuItem7: typeof NavMenuItem;
  navMenuItem8: typeof NavMenuItem;
  navMenuItem9: typeof NavMenuItem;
  navMenuItem10: typeof NavMenuItem;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSideBarNavigation__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSideBarNavigation__VariantsArgs;
    args?: PlasmicSideBarNavigation__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSideBarNavigation__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSideBarNavigation__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSideBarNavigation__ArgProps,
          internalVariantPropNames: PlasmicSideBarNavigation__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSideBarNavigation__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSideBarNavigation";
  } else {
    func.displayName = `PlasmicSideBarNavigation.${nodeName}`;
  }
  return func;
}

export const PlasmicSideBarNavigation = Object.assign(
  // Top-level PlasmicSideBarNavigation renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    sideBar: makeNodeComponent("sideBar"),
    purchasing: makeNodeComponent("purchasing"),
    navMenuItem: makeNodeComponent("navMenuItem"),
    sectionPlanning2: makeNodeComponent("sectionPlanning2"),
    sectionTitlePlanning2: makeNodeComponent("sectionTitlePlanning2"),
    navMenuItem2: makeNodeComponent("navMenuItem2"),
    navMenuItem3: makeNodeComponent("navMenuItem3"),
    navMenuItem4: makeNodeComponent("navMenuItem4"),
    sectionResources: makeNodeComponent("sectionResources"),
    sectionTitleResources: makeNodeComponent("sectionTitleResources"),
    navMenuItem5: makeNodeComponent("navMenuItem5"),
    navMenuItem6: makeNodeComponent("navMenuItem6"),
    navMenuItem7: makeNodeComponent("navMenuItem7"),
    navMenuItem8: makeNodeComponent("navMenuItem8"),
    navMenuItem9: makeNodeComponent("navMenuItem9"),
    navMenuItem10: makeNodeComponent("navMenuItem10"),

    // Metadata about props expected for PlasmicSideBarNavigation
    internalVariantProps: PlasmicSideBarNavigation__VariantProps,
    internalArgProps: PlasmicSideBarNavigation__ArgProps
  }
);

export default PlasmicSideBarNavigation;
/* prettier-ignore-end */
