/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 924bXs3onQpKzyMi97MqJv
// Component: FijYDT0Y_nrh

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import MainPageLayout from "../../MainPageLayout"; // plasmic-import: DrT2KorolVO7/component
import { RichTable } from "@plasmicpkgs/plasmic-rich-components/skinny/rich-table";
import { tableHelpers as RichTable_Helpers } from "@plasmicpkgs/plasmic-rich-components/skinny/rich-table";
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 924bXs3onQpKzyMi97MqJv/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 924bXs3onQpKzyMi97MqJv/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 924bXs3onQpKzyMi97MqJv/projectcss
import sty from "./PlasmicJobCosting.module.css"; // plasmic-import: FijYDT0Y_nrh/css

createPlasmicElementProxy;

export type PlasmicJobCosting__VariantMembers = {};
export type PlasmicJobCosting__VariantsArgs = {};
type VariantPropType = keyof PlasmicJobCosting__VariantsArgs;
export const PlasmicJobCosting__VariantProps = new Array<VariantPropType>();

export type PlasmicJobCosting__ArgsType = {};
type ArgPropType = keyof PlasmicJobCosting__ArgsType;
export const PlasmicJobCosting__ArgProps = new Array<ArgPropType>();

export type PlasmicJobCosting__OverridesType = {
  root?: Flex__<"div">;
  mainPageLayout?: Flex__<typeof MainPageLayout>;
  section?: Flex__<"section">;
  table?: Flex__<typeof RichTable>;
};

export interface DefaultJobCostingProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicJobCosting__RenderFunc(props: {
  variants: PlasmicJobCosting__VariantsArgs;
  args: PlasmicJobCosting__ArgsType;
  overrides: PlasmicJobCosting__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  let [$queries, setDollarQueries] = React.useState<
    Record<string, ReturnType<typeof usePlasmicDataOp>>
  >({});
  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "table.selectedRowKey",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("selectedRowKey", RichTable_Helpers)
      },
      {
        path: "table.selectedRow",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("selectedRow", RichTable_Helpers)
      },
      {
        path: "table.selectedRows",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("selectedRows", RichTable_Helpers)
      },
      {
        path: "table.selectedRowKeys",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("selectedRowKeys", RichTable_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $refs
  });

  const new$Queries: Record<string, ReturnType<typeof usePlasmicDataOp>> = {
    query: usePlasmicDataOp(() => {
      return {
        sourceId: "8Mkd8UGJcnWHCXJeMUwXt8",
        opId: "060100df-1532-4883-b3be-2a099ad17f64",
        userArgs: {},
        cacheKey: `plasmic.$.060100df-1532-4883-b3be-2a099ad17f64.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);

    $queries = new$Queries;
  }

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <MainPageLayout
            data-plasmic-name={"mainPageLayout"}
            data-plasmic-override={overrides.mainPageLayout}
          >
            <section
              data-plasmic-name={"section"}
              data-plasmic-override={overrides.section}
              className={classNames(projectcss.all, sty.section)}
            >
              {(() => {
                const child$Props = {
                  canSelectRows: "multiple",
                  className: classNames("__wab_instance", sty.table),
                  data: (() => {
                    try {
                      return $queries.query;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })(),
                  fields: (() => {
                    const __composite = [
                      {
                        key: "__airtable_id",
                        fieldId: "__airtable_id",
                        isHidden: null
                      },
                      { key: "PO Number", fieldId: "PO Number" },
                      { key: "Generate PO", fieldId: "Generate PO" },
                      { key: "Job Link", fieldId: "Job Link" },
                      {
                        key: "Schedule Item Sync",
                        fieldId: "Schedule Item Sync"
                      },
                      { key: "Vendor Status", fieldId: "Vendor Status" },
                      { key: "Vendor_Link", fieldId: "Vendor_Link" },
                      { key: "Order Total", fieldId: "Order Total" },
                      {
                        key: "Purchase Order Document",
                        fieldId: "Purchase Order Document"
                      },
                      { key: "PO Group", fieldId: "PO Group" },
                      { key: "recId", fieldId: "recId" },
                      {
                        key: "Back Charges_sync",
                        fieldId: "Back Charges_sync"
                      },
                      { key: "VPO Submitted by", fieldId: "VPO Submitted by" },
                      { key: "Inbox Counter", fieldId: "Inbox Counter" },
                      { key: "Inbox Show", fieldId: "Inbox Show" },
                      { key: "PO Status", fieldId: "PO Status" },
                      {
                        key: "Legacy PO Cost Code #",
                        fieldId: "Legacy PO Cost Code #"
                      },
                      { key: "VPO", fieldId: "VPO" },
                      { key: "Cost Code", fieldId: "Cost Code" },
                      { key: "Code Code #", fieldId: "Code Code #" },
                      {
                        key: "Lot# (from Job Link)",
                        fieldId: "Lot# (from Job Link)"
                      },
                      {
                        key: "Schedule Item Identifier",
                        fieldId: "Schedule Item Identifier"
                      },
                      { key: "Doc Date", fieldId: "Doc Date" },
                      { key: "Description", fieldId: "Description" },
                      { key: "Reason Code", fieldId: "Reason Code" },
                      { key: "PO General Notes", fieldId: "PO General Notes" },
                      { key: "Vendor", fieldId: "Vendor" },
                      { key: "Vendor Code", fieldId: "Vendor Code" },
                      { key: "PO Closed", fieldId: "PO Closed" },
                      {
                        key: "Vendor Material Status",
                        fieldId: "Vendor Material Status"
                      },
                      {
                        key: "TYPE (from Vendor_Link)",
                        fieldId: "TYPE (from Vendor_Link)"
                      },
                      { key: "Vendor Import", fieldId: "Vendor Import" },
                      { key: "Vendor Address", fieldId: "Vendor Address" },
                      { key: "PO Contact", fieldId: "PO Contact" },
                      { key: "PO Contact Phone", fieldId: "PO Contact Phone" },
                      {
                        key: "PO Job Costing Line Items",
                        fieldId: "PO Job Costing Line Items"
                      },
                      {
                        key: "Job Costing Items",
                        fieldId: "Job Costing Items"
                      },
                      { key: "Order Sub Total", fieldId: "Order Sub Total" },
                      { key: "PO URL Link", fieldId: "PO URL Link" },
                      { key: "Date_Current", fieldId: "Date_Current" },
                      { key: "extract job", fieldId: "extract job" },
                      { key: "PO Line Items", fieldId: "PO Line Items" },
                      { key: "Lot #", fieldId: "Lot #" },
                      { key: "Lot Address", fieldId: "Lot Address" },
                      { key: "Subdivision", fieldId: "Subdivision" },
                      { key: "Model", fieldId: "Model" },
                      { key: "Vendor Name_LU", fieldId: "Vendor Name_LU" },
                      { key: "Release PO", fieldId: "Release PO" },
                      { key: "PO Title Display", fieldId: "PO Title Display" },
                      { key: "Invoice Link", fieldId: "Invoice Link" },
                      { key: "Linked_PO", fieldId: "Linked_PO" },
                      { key: "PO Email(s)", fieldId: "PO Email(s)" },
                      { key: "View PO", fieldId: "View PO" },
                      { key: "PO View", fieldId: "PO View" },
                      { key: "Get PO List URL", fieldId: "Get PO List URL" },
                      { key: "PO Archive", fieldId: "PO Archive" },
                      { key: "Tax", fieldId: "Tax" },
                      {
                        key: "Service Fee Description",
                        fieldId: "Service Fee Description"
                      },
                      {
                        key: "PO Document Description",
                        fieldId: "PO Document Description"
                      },
                      { key: "Email Notes", fieldId: "Email Notes" },
                      {
                        key: "Additional PO Recipients",
                        fieldId: "Additional PO Recipients"
                      },
                      { key: "PO Sent", fieldId: "PO Sent" },
                      { key: "Printed Date", fieldId: "Printed Date" },
                      { key: "PO Display", fieldId: "PO Display" },
                      {
                        key: "Approve for Payment",
                        fieldId: "Approve for Payment"
                      },
                      { key: "Send PO", fieldId: "Send PO" },
                      {
                        key: "Variance (from PO Line Items)",
                        fieldId: "Variance (from PO Line Items)"
                      },
                      {
                        key: "Reason Code (from PO Line Items)",
                        fieldId: "Reason Code (from PO Line Items)"
                      },
                      {
                        key: "Job Name (Dynamic Filter)",
                        fieldId: "Job Name (Dynamic Filter)"
                      },
                      { key: "Full Lot #", fieldId: "Full Lot #" },
                      {
                        key: "Task Status (from Schedule Item Sync)",
                        fieldId: "Task Status (from Schedule Item Sync)"
                      },
                      { key: "Internal PO", fieldId: "Internal PO" },
                      { key: "Copy to Job", fieldId: "Copy to Job" },
                      { key: "Created", fieldId: "Created" },
                      { key: "Copy to Job Name", fieldId: "Copy to Job Name" },
                      { key: "Select", fieldId: "Select" },
                      {
                        key: "Schedule PO Identifier",
                        fieldId: "Schedule PO Identifier"
                      },
                      { key: "Non Scheduled PO", fieldId: "Non Scheduled PO" },
                      { key: "PO Job Summary", fieldId: "PO Job Summary" },
                      {
                        key: "Expected POs (from PO Job Summary)",
                        fieldId: "Expected POs (from PO Job Summary)"
                      },
                      { key: "ePO_match_found", fieldId: "ePO_match_found" },
                      {
                        key: "Order Total_toString",
                        fieldId: "Order Total_toString"
                      },
                      { key: "Order Total_Num5", fieldId: "Order Total_Num5" },
                      {
                        key: "queue_AddLineItems",
                        fieldId: "queue_AddLineItems"
                      },
                      { key: "extract_PO Group", fieldId: "extract_PO Group" },
                      {
                        key: "extract_ Scheduled Assignee",
                        fieldId: "extract_ Scheduled Assignee"
                      },
                      { key: "Release Phase", fieldId: "Release Phase" },
                      { key: "Created By", fieldId: "Created By" },
                      { key: "Last Modified By", fieldId: "Last Modified By" },
                      { key: "Created 2", fieldId: "Created 2" },
                      {
                        key: "PO last Generated",
                        fieldId: "PO last Generated"
                      },
                      {
                        key: "PlumSail_Purchase Order Document",
                        fieldId: "PlumSail_Purchase Order Document"
                      },
                      {
                        key: "Internal PO (from Vendor_Link)",
                        fieldId: "Internal PO (from Vendor_Link)"
                      },
                      {
                        key: "Billing_PO Schedule Info",
                        fieldId: "Billing_PO Schedule Info"
                      },
                      {
                        key: "Task Status for Billing",
                        fieldId: "Task Status for Billing"
                      },
                      { key: "Latest Release", fieldId: "Latest Release" },
                      { key: "PO Last Modified", fieldId: "PO Last Modified" },
                      {
                        key: "Item Total (from PO Line Items)",
                        fieldId: "Item Total (from PO Line Items)"
                      },
                      {
                        key: "Partial Verification Log",
                        fieldId: "Partial Verification Log"
                      },
                      {
                        key: "Task Projected (from Schedule Item Sync)",
                        fieldId: "Task Projected (from Schedule Item Sync)"
                      },
                      {
                        key: "Timing (from Schedule Item Sync)",
                        fieldId: "Timing (from Schedule Item Sync)"
                      },
                      {
                        key: "Task Timing Projection Display",
                        fieldId: "Task Timing Projection Display"
                      },
                      { key: "Link to Self", fieldId: "Link to Self" },
                      {
                        key: "Available (from Job Link)",
                        fieldId: "Available (from Job Link)"
                      },
                      { key: "Line Items", fieldId: "Line Items" },
                      {
                        key: "Line Items Ordered",
                        fieldId: "Line Items Ordered"
                      },
                      {
                        key: "Line Items at Warehouse",
                        fieldId: "Line Items at Warehouse"
                      },
                      {
                        key: "Line Items Delivered to Job",
                        fieldId: "Line Items Delivered to Job"
                      },
                      {
                        key: "Vendor Order Docs",
                        fieldId: "Vendor Order Docs"
                      },
                      {
                        key: "Vendor Order Notes",
                        fieldId: "Vendor Order Notes"
                      },
                      {
                        key: "Vendor Order Number",
                        fieldId: "Vendor Order Number"
                      },
                      {
                        key: "Vendor Order Date",
                        fieldId: "Vendor Order Date"
                      },
                      {
                        key: "Bulk Update Order Status",
                        fieldId: "Bulk Update Order Status"
                      },
                      { key: "PO Ordered", fieldId: "PO Ordered" },
                      {
                        key: "Complete Progress",
                        fieldId: "Complete Progress"
                      },
                      { key: "choose_Release", fieldId: "choose_Release" },
                      { key: "Match_from EPOs", fieldId: "Match_from EPOs" },
                      {
                        key: "JC Purchase Orders",
                        fieldId: "JC Purchase Orders"
                      },
                      {
                        key: "Order Total (from JC Purchase Orders)",
                        fieldId: "Order Total (from JC Purchase Orders)"
                      },
                      { key: "Total Match", fieldId: "Total Match" },
                      {
                        key: "Order Total_Num5 (from JC Purchase Orders)",
                        fieldId: "Order Total_Num5 (from JC Purchase Orders)"
                      },
                      { key: "isVPO", fieldId: "isVPO" },
                      { key: "DocCheck", fieldId: "DocCheck" },
                      { key: "NF_Cost Code", fieldId: "NF_Cost Code" },
                      { key: "Billing Table", fieldId: "Billing Table" },
                      { key: "Back Charge VPO", fieldId: "Back Charge VPO" },
                      {
                        key: "PO Line_CC_Highest Dollar",
                        fieldId: "PO Line_CC_Highest Dollar"
                      },
                      {
                        key: "CC_Billing Line Loader",
                        fieldId: "CC_Billing Line Loader"
                      },
                      {
                        key: "Partner Change Request Intake",
                        fieldId: "Partner Change Request Intake"
                      },
                      {
                        key: "Partner Change Request Log",
                        fieldId: "Partner Change Request Log"
                      },
                      {
                        key: "Partner Change Request Entry",
                        fieldId: "Partner Change Request Entry"
                      },
                      {
                        key: "Change Request Attachments",
                        fieldId: "Change Request Attachments"
                      },
                      {
                        key: "Last Change Request",
                        fieldId: "Last Change Request"
                      },
                      {
                        key: "Notes (from Back Charges_sync)",
                        fieldId: "Notes (from Back Charges_sync)"
                      },
                      {
                        key: "Parent Purchase Order",
                        fieldId: "Parent Purchase Order"
                      },
                      {
                        key: "PO Number (from Parent Purchase Order)",
                        fieldId: "PO Number (from Parent Purchase Order)"
                      },
                      { key: "Linked VPOs", fieldId: "Linked VPOs" },
                      { key: "Count VPOs", fieldId: "Count VPOs" },
                      {
                        key: "LU_Parent VPO COUNT",
                        fieldId: "LU_Parent VPO COUNT"
                      },
                      { key: "VPO Count", fieldId: "VPO Count" },
                      {
                        key: "trigger_parent purchase order",
                        fieldId: "trigger_parent purchase order"
                      },
                      { key: "VPO Next_Index", fieldId: "VPO Next_Index" },
                      {
                        key: "PO List _ URL Link",
                        fieldId: "PO List _ URL Link"
                      },
                      { key: "VPO Status", fieldId: "VPO Status" },
                      { key: "Projected Date", fieldId: "Projected Date" },
                      { key: "Delivery Display", fieldId: "Delivery Display" },
                      {
                        key: "Change Requested by",
                        fieldId: "Change Requested by"
                      },
                      {
                        key: "VPO Request Attachments",
                        fieldId: "VPO Request Attachments"
                      },
                      { key: "Request Handler", fieldId: "Request Handler" },
                      {
                        key: "SS_Trigger Update",
                        fieldId: "SS_Trigger Update"
                      },
                      { key: "SS Last Modified", fieldId: "SS Last Modified" },
                      { key: "Assignee", fieldId: "Assignee" },
                      {
                        key: "Push Update to SS",
                        fieldId: "Push Update to SS"
                      },
                      {
                        key: "Non-Scheduled List",
                        fieldId: "Non-Scheduled List"
                      },
                      { key: "Work Status", fieldId: "Work Status" },
                      { key: "Web.Modified by", fieldId: "Web.Modified by" },
                      {
                        key: "BBS Accounting_Job for PO Line",
                        fieldId: "BBS Accounting_Job for PO Line"
                      },
                      {
                        key: "PO Email Sender (from Vendor_Link)",
                        fieldId: "PO Email Sender (from Vendor_Link)"
                      },
                      {
                        key: "PO Communication Log",
                        fieldId: "PO Communication Log"
                      },
                      {
                        key: "Back Charges_sync copy",
                        fieldId: "Back Charges_sync copy"
                      },
                      {
                        key: "Item Description (from PO Line Items)",
                        fieldId: "Item Description (from PO Line Items)"
                      },
                      {
                        key: "Purchase Order Type",
                        fieldId: "Purchase Order Type"
                      },
                      { key: "DUPLICATE", fieldId: "DUPLICATE" },
                      { key: "Dup PO Staging", fieldId: "Dup PO Staging" },
                      {
                        key: "Schedule Partner Check",
                        fieldId: "Schedule Partner Check"
                      },
                      {
                        key: "Has been Released (Historical Check)",
                        fieldId: "Has been Released (Historical Check)"
                      },
                      {
                        key: "Scheduled Assignee (from Schedule Item Sync)",
                        fieldId: "Scheduled Assignee (from Schedule Item Sync)"
                      },
                      {
                        key: "Field_Verify All Items",
                        fieldId: "Field_Verify All Items"
                      },
                      { key: "RFIoQ", fieldId: "RFIoQ" },
                      {
                        key: "Last Modified (from Schedule Item Sync)",
                        fieldId: "Last Modified (from Schedule Item Sync)"
                      },
                      {
                        key: "Last Updated by (from Schedule Item Sync)",
                        fieldId: "Last Updated by (from Schedule Item Sync)"
                      },
                      {
                        key: "Task Updated By: (from Schedule Item Sync)",
                        fieldId: "Task Updated By: (from Schedule Item Sync)"
                      },
                      {
                        key: "partnerUserCheckDisplay",
                        fieldId: "partnerUserCheckDisplay"
                      },
                      { key: "PartnerUserCheck", fieldId: "PartnerUserCheck" },
                      {
                        key: "nameScheduledAssignee",
                        fieldId: "nameScheduledAssignee"
                      },
                      { key: "namePOGroup", fieldId: "namePOGroup" },
                      { key: "scheduleStatus", fieldId: "scheduleStatus" },
                      { key: "PO <-> Schedule", fieldId: "PO <-> Schedule" },
                      { key: "scheduleJoinKey", fieldId: "scheduleJoinKey" },
                      {
                        key: "scheduleJoinStatus",
                        fieldId: "scheduleJoinStatus"
                      },
                      {
                        key: "scheduleMatchKeyPOGroup",
                        fieldId: "scheduleMatchKeyPOGroup"
                      },
                      {
                        key: "existingJoinCount",
                        fieldId: "existingJoinCount"
                      },
                      { key: "testManualSync", fieldId: "testManualSync" },
                      { key: "FieldAttachments", fieldId: "FieldAttachments" },
                      { key: "poScheduleCheck", fieldId: "poScheduleCheck" },
                      {
                        key: "Status (from Back Charges_sync)",
                        fieldId: "Status (from Back Charges_sync)"
                      },
                      {
                        key: "fieldCountNonVerifiedItems",
                        fieldId: "fieldCountNonVerifiedItems"
                      },
                      {
                        key: "Superintendent (from pmJobSync) (from Job Link)",
                        fieldId:
                          "Superintendent (from pmJobSync) (from Job Link)"
                      }
                    ];
                    __composite["0"]["isHidden"] = true;
                    return __composite;
                  })(),

                  hideSelectionBar: false,
                  onRowSelectionChanged: async (...eventArgs: any) => {
                    generateStateOnChangePropForCodeComponents(
                      $state,
                      "selectedRowKey",
                      ["table", "selectedRowKey"],
                      RichTable_Helpers
                    ).apply(null, eventArgs);
                    generateStateOnChangePropForCodeComponents(
                      $state,
                      "selectedRow",
                      ["table", "selectedRow"],
                      RichTable_Helpers
                    ).apply(null, eventArgs);
                    generateStateOnChangePropForCodeComponents(
                      $state,
                      "selectedRows",
                      ["table", "selectedRows"],
                      RichTable_Helpers
                    ).apply(null, eventArgs);
                    generateStateOnChangePropForCodeComponents(
                      $state,
                      "selectedRowKeys",
                      ["table", "selectedRowKeys"],
                      RichTable_Helpers
                    ).apply(null, eventArgs);
                  },
                  rowActions: [],
                  scopeClassName: sty["table__instance"],
                  selectedRowKey: generateStateValueProp($state, [
                    "table",
                    "selectedRowKey"
                  ]),
                  selectedRowKeys: generateStateValueProp($state, [
                    "table",
                    "selectedRowKeys"
                  ]),
                  themeResetClassName: classNames(
                    projectcss.root_reset,
                    projectcss.root_reset_tags,
                    projectcss.plasmic_default_styles,
                    projectcss.plasmic_mixins,
                    styleTokensClassNames
                  )
                };
                initializeCodeComponentStates(
                  $state,
                  [
                    {
                      name: "selectedRowKey",
                      plasmicStateName: "table.selectedRowKey"
                    },
                    {
                      name: "selectedRow",
                      plasmicStateName: "table.selectedRow"
                    },
                    {
                      name: "selectedRows",
                      plasmicStateName: "table.selectedRows"
                    },
                    {
                      name: "selectedRowKeys",
                      plasmicStateName: "table.selectedRowKeys"
                    }
                  ],
                  [],
                  RichTable_Helpers ?? {},
                  child$Props
                );

                return (
                  <RichTable
                    data-plasmic-name={"table"}
                    data-plasmic-override={overrides.table}
                    {...child$Props}
                  />
                );
              })()}
            </section>
          </MainPageLayout>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "mainPageLayout", "section", "table"],
  mainPageLayout: ["mainPageLayout", "section", "table"],
  section: ["section", "table"],
  table: ["table"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  mainPageLayout: typeof MainPageLayout;
  section: "section";
  table: typeof RichTable;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicJobCosting__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicJobCosting__VariantsArgs;
    args?: PlasmicJobCosting__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicJobCosting__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicJobCosting__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicJobCosting__ArgProps,
          internalVariantPropNames: PlasmicJobCosting__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicJobCosting__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicJobCosting";
  } else {
    func.displayName = `PlasmicJobCosting.${nodeName}`;
  }
  return func;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "924bXs3onQpKzyMi97MqJv"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicJobCosting = Object.assign(
  // Top-level PlasmicJobCosting renders the root element
  withUsePlasmicAuth(makeNodeComponent("root")),
  {
    // Helper components rendering sub-elements
    mainPageLayout: makeNodeComponent("mainPageLayout"),
    section: makeNodeComponent("section"),
    table: makeNodeComponent("table"),

    // Metadata about props expected for PlasmicJobCosting
    internalVariantProps: PlasmicJobCosting__VariantProps,
    internalArgProps: PlasmicJobCosting__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicJobCosting;
/* prettier-ignore-end */
