/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 924bXs3onQpKzyMi97MqJv
// Component: T4yFeDDIFep_

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import MainPageLayout from "../../MainPageLayout"; // plasmic-import: DrT2KorolVO7/component
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { RichList } from "@plasmicpkgs/plasmic-rich-components/skinny/rich-list";
import { AntdSelect } from "@plasmicpkgs/antd5/skinny/registerSelect";
import { AntdProgress } from "@plasmicpkgs/antd5/skinny/registerProgress";
import ListItemWithHeader from "../../ListItemWithHeader"; // plasmic-import: oczCFi_qY_EP/component
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 924bXs3onQpKzyMi97MqJv/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 924bXs3onQpKzyMi97MqJv/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 924bXs3onQpKzyMi97MqJv/projectcss
import sty from "./PlasmicPurchaseOrdersMain.module.css"; // plasmic-import: T4yFeDDIFep_/css

createPlasmicElementProxy;

export type PlasmicPurchaseOrdersMain__VariantMembers = {};
export type PlasmicPurchaseOrdersMain__VariantsArgs = {};
type VariantPropType = keyof PlasmicPurchaseOrdersMain__VariantsArgs;
export const PlasmicPurchaseOrdersMain__VariantProps =
  new Array<VariantPropType>();

export type PlasmicPurchaseOrdersMain__ArgsType = {};
type ArgPropType = keyof PlasmicPurchaseOrdersMain__ArgsType;
export const PlasmicPurchaseOrdersMain__ArgProps = new Array<ArgPropType>();

export type PlasmicPurchaseOrdersMain__OverridesType = {
  root?: Flex__<"div">;
  mainPageLayout?: Flex__<typeof MainPageLayout>;
  mainPageStack?: Flex__<"div">;
  pageHeader?: Flex__<"div">;
  dataList?: Flex__<typeof RichList>;
  statusSelect?: Flex__<typeof AntdSelect>;
  contentStack?: Flex__<"div">;
  poTitle?: Flex__<"div">;
  progress?: Flex__<typeof AntdProgress>;
  pagnination?: Flex__<"div">;
  firstPage?: Flex__<"div">;
};

export interface DefaultPurchaseOrdersMainProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPurchaseOrdersMain__RenderFunc(props: {
  variants: PlasmicPurchaseOrdersMain__VariantsArgs;
  args: PlasmicPurchaseOrdersMain__ArgsType;
  overrides: PlasmicPurchaseOrdersMain__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const currentUser = useCurrentUser?.() || {};

  let [$queries, setDollarQueries] = React.useState<
    Record<string, ReturnType<typeof usePlasmicDataOp>>
  >({});
  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "currentPage",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "poDataCache",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => ({})
      },
      {
        path: "variable",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "statusSelect.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $refs
  });

  const new$Queries: Record<string, ReturnType<typeof usePlasmicDataOp>> = {
    getPurchaseOrders: usePlasmicDataOp(() => {
      return {
        sourceId: "8Mkd8UGJcnWHCXJeMUwXt8",
        opId: "db56fe35-d052-4361-8486-8c7b99c261dc",
        userArgs: {},
        cacheKey: `plasmic.$.db56fe35-d052-4361-8486-8c7b99c261dc.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);

    $queries = new$Queries;
  }

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <MainPageLayout
            data-plasmic-name={"mainPageLayout"}
            data-plasmic-override={overrides.mainPageLayout}
            className={classNames("__wab_instance", sty.mainPageLayout)}
          >
            <div
              data-plasmic-name={"mainPageStack"}
              data-plasmic-override={overrides.mainPageStack}
              className={classNames(projectcss.all, sty.mainPageStack)}
            >
              <div
                data-plasmic-name={"pageHeader"}
                data-plasmic-override={overrides.pageHeader}
                className={classNames(projectcss.all, sty.pageHeader)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__rm4Ht)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___58HKs)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___0TGvj
                      )}
                    >
                      {"Purchase Orders"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ubSs1
                      )}
                    >
                      {
                        "Create, manage, and track POs sent to partners based on job-specific kits and pricing"
                      }
                    </div>
                  </div>
                  <AntdButton
                    className={classNames("__wab_instance", sty.button__jLchx)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bWnnD
                      )}
                    >
                      {"Button"}
                    </div>
                  </AntdButton>
                </div>
                <RichList
                  data-plasmic-name={"dataList"}
                  data-plasmic-override={overrides.dataList}
                  bordered={true}
                  className={classNames("__wab_instance", sty.dataList)}
                  header={(_par =>
                    !_par ? [] : Array.isArray(_par) ? _par : [_par])(
                    (() => {
                      try {
                        return $queries.getPurchaseOrders.data;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return [];
                        }
                        throw e;
                      }
                    })()
                  ).map((__plasmic_item_0, __plasmic_idx_0) => {
                    const currentItem = __plasmic_item_0;
                    const currentIndex = __plasmic_idx_0;
                    return (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__gJsb6
                        )}
                        key={currentIndex}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__mV3B5
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return currentItem["PO Number"];
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__auSnu
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return currentItem.Vendor[0];
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zp7E1
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return currentItem[
                                  "Order Total"
                                ].toLocaleString("en-US", {
                                  style: "currency",
                                  currency: "USD"
                                });
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "items description";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </div>
                    );
                  })}
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__pwkc7)}>
                <AntdSelect
                  data-plasmic-name={"statusSelect"}
                  data-plasmic-override={overrides.statusSelect}
                  className={classNames("__wab_instance", sty.statusSelect)}
                  defaultStylesClassName={classNames(
                    projectcss.root_reset,
                    projectcss.plasmic_default_styles,
                    projectcss.plasmic_mixins,
                    styleTokensClassNames
                  )}
                  mode={"multiple"}
                  onChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "statusSelect",
                      "value"
                    ]).apply(null, eventArgs);
                  }}
                  options={(() => {
                    const __composite = [
                      { value: null, label: null, type: "option" },
                      { value: null, label: null, type: "option" },
                      { type: "option", value: null, label: null }
                    ];
                    __composite["0"]["value"] = "Pending Approval";
                    __composite["0"]["label"] = "Pending Approval";
                    __composite["1"]["value"] = "Approved";
                    __composite["1"]["label"] = "Approved";
                    __composite["2"]["value"] = "VPO Requested";
                    __composite["2"]["label"] = "VPO Requested";
                    return __composite;
                  })()}
                  placeholder={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__szWSe
                      )}
                    >
                      {"Status..."}
                    </div>
                  }
                  popupScopeClassName={sty["statusSelect__popup"]}
                  value={generateStateValueProp($state, [
                    "statusSelect",
                    "value"
                  ])}
                />
              </div>
              <div
                data-plasmic-name={"contentStack"}
                data-plasmic-override={overrides.contentStack}
                className={classNames(projectcss.all, sty.contentStack)}
              >
                {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
                  (() => {
                    try {
                      return ($queries.getPurchaseOrders.data || [])
                        .filter(po =>
                          !$state.statusSelect.value ||
                          $state.statusSelect.value.length === 0
                            ? true
                            : $state.statusSelect.value.includes(
                                po["Vendor Status"]
                              )
                        )
                        .slice(
                          $state.currentPage * 50,
                          $state.currentPage * 50 + 50
                        );
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return [];
                      }
                      throw e;
                    }
                  })()
                ).map((__plasmic_item_0, __plasmic_idx_0) => {
                  const currentItem = __plasmic_item_0;
                  const currentIndex = __plasmic_idx_0;
                  return (
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___3OqCb
                      )}
                      key={currentIndex}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__rd4Qx
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ur97T
                          )}
                        >
                          <div
                            data-plasmic-name={"poTitle"}
                            data-plasmic-override={overrides.poTitle}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.poTitle
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return currentItem["PO Number"];
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                          <AntdProgress
                            data-plasmic-name={"progress"}
                            data-plasmic-override={overrides.progress}
                            className={classNames(
                              "__wab_instance",
                              sty.progress
                            )}
                            percent={(() => {
                              try {
                                return (
                                  Math.round(
                                    currentItem?.accountingPOUsage?.[0] *
                                      100 *
                                      10
                                  ) / 10
                                );
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return 0;
                                }
                                throw e;
                              }
                            })()}
                            size={"default"}
                            strokeColor={(() => {
                              try {
                                return currentItem?.accountingPOUsage?.[0] > 1
                                  ? "System: Error Active"
                                  : currentItem?.accountingPOUsage?.[0] === 1
                                    ? "System: Primary"
                                    : "System: Primary";
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "var(--token-iWQmILTzm3N0)";
                                }
                                throw e;
                              }
                            })()}
                            type={"line"}
                          />
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___2T9Vp
                          )}
                        >
                          <ListItemWithHeader
                            className={classNames(
                              "__wab_instance",
                              sty.listItemWithHeader__jweFf
                            )}
                            columnName={"Partner"}
                            itemDescription={(() => {
                              try {
                                return currentItem.Vendor[0];
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })()}
                          />

                          <ListItemWithHeader
                            className={classNames(
                              "__wab_instance",
                              sty.listItemWithHeader__tXyRq
                            )}
                            columnName={"Order Total"}
                            itemDescription={(() => {
                              try {
                                return currentItem[
                                  "Order Total"
                                ].toLocaleString("en-US", {
                                  style: "currency",
                                  currency: "USD"
                                });
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })()}
                          />

                          <ListItemWithHeader
                            className={classNames(
                              "__wab_instance",
                              sty.listItemWithHeader__ivFu
                            )}
                            columnName={"Last Modified"}
                            itemDescription={(() => {
                              try {
                                return (() => {
                                  const date = new Date(
                                    currentItem["PO Last Modified"]
                                  );
                                  const options = {
                                    month: "2-digit",
                                    day: "2-digit",
                                    year: "numeric",
                                    hour: "2-digit",
                                    minute: "2-digit",
                                    hour12: true
                                  };
                                  return date.toLocaleString("en-US", options);
                                })();
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })()}
                          />

                          <ListItemWithHeader
                            className={classNames(
                              "__wab_instance",
                              sty.listItemWithHeader__iz4Br
                            )}
                            columnName={"Latest Release"}
                            itemDescription={(() => {
                              try {
                                return new Date(
                                  currentItem["PO Last Modified"]
                                ).toLocaleString("en-US", {
                                  month: "numeric",
                                  day: "2-digit",
                                  year: "numeric",
                                  hour: "2-digit",
                                  minute: "2-digit",
                                  hour12: true
                                });
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })()}
                          />

                          <ListItemWithHeader
                            className={classNames(
                              "__wab_instance",
                              sty.listItemWithHeader___0AGj7
                            )}
                            columnName={"Status"}
                            itemDescription={(() => {
                              try {
                                return currentItem["Vendor Status"];
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })()}
                          />
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
              <div
                data-plasmic-name={"pagnination"}
                data-plasmic-override={overrides.pagnination}
                className={classNames(projectcss.all, sty.pagnination)}
              >
                {(() => {
                  try {
                    return $state.currentPage > 0;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return true;
                    }
                    throw e;
                  }
                })() ? (
                  <AntdButton
                    className={classNames("__wab_instance", sty.button__evyIn)}
                    onClick={async () => {
                      const $steps = {};

                      $steps["updateCurrentPage"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["currentPage"]
                              },
                              operation: 0,
                              value: 0
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;

                              $stateSet(objRoot, variablePath, value);
                              return value;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateCurrentPage"] != null &&
                        typeof $steps["updateCurrentPage"] === "object" &&
                        typeof $steps["updateCurrentPage"].then === "function"
                      ) {
                        $steps["updateCurrentPage"] =
                          await $steps["updateCurrentPage"];
                      }
                    }}
                  >
                    <div
                      data-plasmic-name={"firstPage"}
                      data-plasmic-override={overrides.firstPage}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.firstPage
                      )}
                    >
                      {"|<"}
                    </div>
                  </AntdButton>
                ) : null}
                {(() => {
                  try {
                    return $state.currentPage > 0;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return true;
                    }
                    throw e;
                  }
                })() ? (
                  <AntdButton
                    className={classNames("__wab_instance", sty.button__zeoqi)}
                    onClick={async () => {
                      const $steps = {};

                      $steps["updateCurrentPage"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["currentPage"]
                              },
                              operation: 3
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;

                              const oldValue = $stateGet(objRoot, variablePath);
                              $stateSet(objRoot, variablePath, oldValue - 1);
                              return oldValue - 1;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateCurrentPage"] != null &&
                        typeof $steps["updateCurrentPage"] === "object" &&
                        typeof $steps["updateCurrentPage"].then === "function"
                      ) {
                        $steps["updateCurrentPage"] =
                          await $steps["updateCurrentPage"];
                      }
                    }}
                  >
                    {(() => {
                      try {
                        return true;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return true;
                        }
                        throw e;
                      }
                    })() ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__szel0
                        )}
                      >
                        {"<< Previous"}
                      </div>
                    ) : null}
                  </AntdButton>
                ) : null}
                <AntdButton
                  className={classNames("__wab_instance", sty.button__zTkRm)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___4NGP
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $state.currentPage === 0
                            ? 1
                            : $state.currentPage + 1;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "Next >";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </div>
                </AntdButton>
                <AntdButton
                  className={classNames("__wab_instance", sty.button__fzBDi)}
                  onClick={async () => {
                    const $steps = {};

                    $steps["updateCurrentPage"] = true
                      ? (() => {
                          const actionArgs = {
                            variable: {
                              objRoot: $state,
                              variablePath: ["currentPage"]
                            },
                            operation: 2
                          };
                          return (({
                            variable,
                            value,
                            startIndex,
                            deleteCount
                          }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;

                            const oldValue = $stateGet(objRoot, variablePath);
                            $stateSet(objRoot, variablePath, oldValue + 1);
                            return oldValue + 1;
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["updateCurrentPage"] != null &&
                      typeof $steps["updateCurrentPage"] === "object" &&
                      typeof $steps["updateCurrentPage"].then === "function"
                    ) {
                      $steps["updateCurrentPage"] =
                        await $steps["updateCurrentPage"];
                    }
                  }}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xVEr9
                    )}
                  >
                    {"Next >>"}
                  </div>
                </AntdButton>
              </div>
            </div>
          </MainPageLayout>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "mainPageLayout",
    "mainPageStack",
    "pageHeader",
    "dataList",
    "statusSelect",
    "contentStack",
    "poTitle",
    "progress",
    "pagnination",
    "firstPage"
  ],
  mainPageLayout: [
    "mainPageLayout",
    "mainPageStack",
    "pageHeader",
    "dataList",
    "statusSelect",
    "contentStack",
    "poTitle",
    "progress",
    "pagnination",
    "firstPage"
  ],
  mainPageStack: [
    "mainPageStack",
    "pageHeader",
    "dataList",
    "statusSelect",
    "contentStack",
    "poTitle",
    "progress",
    "pagnination",
    "firstPage"
  ],
  pageHeader: ["pageHeader", "dataList"],
  dataList: ["dataList"],
  statusSelect: ["statusSelect"],
  contentStack: ["contentStack", "poTitle", "progress"],
  poTitle: ["poTitle"],
  progress: ["progress"],
  pagnination: ["pagnination", "firstPage"],
  firstPage: ["firstPage"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  mainPageLayout: typeof MainPageLayout;
  mainPageStack: "div";
  pageHeader: "div";
  dataList: typeof RichList;
  statusSelect: typeof AntdSelect;
  contentStack: "div";
  poTitle: "div";
  progress: typeof AntdProgress;
  pagnination: "div";
  firstPage: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPurchaseOrdersMain__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPurchaseOrdersMain__VariantsArgs;
    args?: PlasmicPurchaseOrdersMain__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicPurchaseOrdersMain__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicPurchaseOrdersMain__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPurchaseOrdersMain__ArgProps,
          internalVariantPropNames: PlasmicPurchaseOrdersMain__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPurchaseOrdersMain__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPurchaseOrdersMain";
  } else {
    func.displayName = `PlasmicPurchaseOrdersMain.${nodeName}`;
  }
  return func;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "924bXs3onQpKzyMi97MqJv"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicPurchaseOrdersMain = Object.assign(
  // Top-level PlasmicPurchaseOrdersMain renders the root element
  withUsePlasmicAuth(makeNodeComponent("root")),
  {
    // Helper components rendering sub-elements
    mainPageLayout: makeNodeComponent("mainPageLayout"),
    mainPageStack: makeNodeComponent("mainPageStack"),
    pageHeader: makeNodeComponent("pageHeader"),
    dataList: makeNodeComponent("dataList"),
    statusSelect: makeNodeComponent("statusSelect"),
    contentStack: makeNodeComponent("contentStack"),
    poTitle: makeNodeComponent("poTitle"),
    progress: makeNodeComponent("progress"),
    pagnination: makeNodeComponent("pagnination"),
    firstPage: makeNodeComponent("firstPage"),

    // Metadata about props expected for PlasmicPurchaseOrdersMain
    internalVariantProps: PlasmicPurchaseOrdersMain__VariantProps,
    internalArgProps: PlasmicPurchaseOrdersMain__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicPurchaseOrdersMain;
/* prettier-ignore-end */
