/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 924bXs3onQpKzyMi97MqJv
// Component: 9g4QnerbojGg

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 924bXs3onQpKzyMi97MqJv/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 924bXs3onQpKzyMi97MqJv/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 924bXs3onQpKzyMi97MqJv/projectcss
import sty from "./PlasmicNavMenuItem.module.css"; // plasmic-import: 9g4QnerbojGg/css

import ClipboardCheckSvgrepoComSvgIcon from "./icons/PlasmicIcon__ClipboardCheckSvgrepoComSvg"; // plasmic-import: gOv0XEqKHtlU/icon

createPlasmicElementProxy;

export type PlasmicNavMenuItem__VariantMembers = {
  itemBorderOn: "itemBorderOn";
};
export type PlasmicNavMenuItem__VariantsArgs = {
  itemBorderOn?: SingleBooleanChoiceArg<"itemBorderOn">;
};
type VariantPropType = keyof PlasmicNavMenuItem__VariantsArgs;
export const PlasmicNavMenuItem__VariantProps = new Array<VariantPropType>(
  "itemBorderOn"
);

export type PlasmicNavMenuItem__ArgsType = {
  menuItemName?: string;
  navLink?: string;
  expanded?: boolean;
  children?: React.ReactNode;
  menuActiveBorder?: boolean;
  highlightActive?: boolean;
  onHighlightActiveChange?: (val: string) => void;
};
type ArgPropType = keyof PlasmicNavMenuItem__ArgsType;
export const PlasmicNavMenuItem__ArgProps = new Array<ArgPropType>(
  "menuItemName",
  "navLink",
  "expanded",
  "children",
  "menuActiveBorder",
  "highlightActive",
  "onHighlightActiveChange"
);

export type PlasmicNavMenuItem__OverridesType = {
  jostCosting?: Flex__<"div">;
  text?: Flex__<"div">;
};

export interface DefaultNavMenuItemProps {
  menuItemName?: string;
  navLink?: string;
  expanded?: boolean;
  children?: React.ReactNode;
  menuActiveBorder?: boolean;
  highlightActive?: boolean;
  onHighlightActiveChange?: (val: string) => void;
  itemBorderOn?: SingleBooleanChoiceArg<"itemBorderOn">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNavMenuItem__RenderFunc(props: {
  variants: PlasmicNavMenuItem__VariantsArgs;
  args: PlasmicNavMenuItem__ArgsType;
  overrides: PlasmicNavMenuItem__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          menuItemName: "Job Costing",
          navLink: `/`,

          expanded: true,
          menuActiveBorder: false
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "itemBorderOn",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.itemBorderOn
      },
      {
        path: "highlightActive",
        type: "writable",
        variableType: "boolean",

        valueProp: "highlightActive",
        onChangeProp: "onHighlightActiveChange"
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"jostCosting"}
      data-plasmic-override={overrides.jostCosting}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.jostCosting,
        {
          [sty.jostCostingitemBorderOn]: hasVariant(
            $state,
            "itemBorderOn",
            "itemBorderOn"
          )
        }
      )}
      onClick={async event => {
        const $steps = {};

        $steps["goToPage"] = true
          ? (() => {
              const actionArgs = {
                destination: (() => {
                  try {
                    return $props.navLink;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return undefined;
                    }
                    throw e;
                  }
                })()
              };
              return (({ destination }) => {
                if (
                  typeof destination === "string" &&
                  destination.startsWith("#")
                ) {
                  document
                    .getElementById(destination.substr(1))
                    .scrollIntoView({ behavior: "smooth" });
                } else {
                  __nextRouter?.push(destination);
                }
              })?.apply(null, [actionArgs]);
            })()
          : undefined;
        if (
          $steps["goToPage"] != null &&
          typeof $steps["goToPage"] === "object" &&
          typeof $steps["goToPage"].then === "function"
        ) {
          $steps["goToPage"] = await $steps["goToPage"];
        }

        $steps["updateActivePage"] = true
          ? (() => {
              const actionArgs = {
                variable: {
                  objRoot: $state,
                  variablePath: ["highlightActive"]
                },
                operation: 0,
                value: true
              };
              return (({ variable, value, startIndex, deleteCount }) => {
                if (!variable) {
                  return;
                }
                const { objRoot, variablePath } = variable;

                $stateSet(objRoot, variablePath, value);
                return value;
              })?.apply(null, [actionArgs]);
            })()
          : undefined;
        if (
          $steps["updateActivePage"] != null &&
          typeof $steps["updateActivePage"] === "object" &&
          typeof $steps["updateActivePage"].then === "function"
        ) {
          $steps["updateActivePage"] = await $steps["updateActivePage"];
        }
      }}
    >
      {renderPlasmicSlot({
        defaultContents: (
          <ClipboardCheckSvgrepoComSvgIcon
            className={classNames(projectcss.all, sty.svg__cCc4G)}
            role={"img"}
          />
        ),

        value: args.children
      })}
      {(() => {
        try {
          return $props.expanded;
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return true;
          }
          throw e;
        }
      })() ? (
        <div
          data-plasmic-name={"text"}
          data-plasmic-override={overrides.text}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text
          )}
        >
          <React.Fragment>
            {(() => {
              try {
                return $props.menuItemName;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "Job Costing";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </div>
      ) : null}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  jostCosting: ["jostCosting", "text"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  jostCosting: "div";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNavMenuItem__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNavMenuItem__VariantsArgs;
    args?: PlasmicNavMenuItem__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicNavMenuItem__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicNavMenuItem__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNavMenuItem__ArgProps,
          internalVariantPropNames: PlasmicNavMenuItem__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNavMenuItem__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "jostCosting") {
    func.displayName = "PlasmicNavMenuItem";
  } else {
    func.displayName = `PlasmicNavMenuItem.${nodeName}`;
  }
  return func;
}

export const PlasmicNavMenuItem = Object.assign(
  // Top-level PlasmicNavMenuItem renders the root element
  makeNodeComponent("jostCosting"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicNavMenuItem
    internalVariantProps: PlasmicNavMenuItem__VariantProps,
    internalArgProps: PlasmicNavMenuItem__ArgProps
  }
);

export default PlasmicNavMenuItem;
/* prettier-ignore-end */
