/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 924bXs3onQpKzyMi97MqJv
// Component: DrT2KorolVO7

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import SideBarNavigation from "../../SideBarNavigation"; // plasmic-import: cG-RUM6LDbn9/component
import { AntdBreadcrumb } from "@plasmicpkgs/antd5/skinny/registerBreadcrumb";
import { AntdBreadcrumbItem } from "@plasmicpkgs/antd5/skinny/registerBreadcrumb";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 924bXs3onQpKzyMi97MqJv/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 924bXs3onQpKzyMi97MqJv/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 924bXs3onQpKzyMi97MqJv/projectcss
import sty from "./PlasmicMainPageLayout.module.css"; // plasmic-import: DrT2KorolVO7/css

createPlasmicElementProxy;

export type PlasmicMainPageLayout__VariantMembers = {};
export type PlasmicMainPageLayout__VariantsArgs = {};
type VariantPropType = keyof PlasmicMainPageLayout__VariantsArgs;
export const PlasmicMainPageLayout__VariantProps = new Array<VariantPropType>();

export type PlasmicMainPageLayout__ArgsType = { children?: React.ReactNode };
type ArgPropType = keyof PlasmicMainPageLayout__ArgsType;
export const PlasmicMainPageLayout__ArgProps = new Array<ArgPropType>(
  "children"
);

export type PlasmicMainPageLayout__OverridesType = {
  root?: Flex__<"div">;
  freeBox?: Flex__<"div">;
  sideBarNavigation?: Flex__<typeof SideBarNavigation>;
  pageContent?: Flex__<"div">;
  pageSection?: Flex__<"section">;
  breadcrumb?: Flex__<typeof AntdBreadcrumb>;
};

export interface DefaultMainPageLayoutProps {
  children?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicMainPageLayout__RenderFunc(props: {
  variants: PlasmicMainPageLayout__VariantsArgs;
  args: PlasmicMainPageLayout__ArgsType;
  overrides: PlasmicMainPageLayout__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "sideBarNavigation.currentPage",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ``
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        <SideBarNavigation
          data-plasmic-name={"sideBarNavigation"}
          data-plasmic-override={overrides.sideBarNavigation}
          className={classNames("__wab_instance", sty.sideBarNavigation)}
          currentPage={generateStateValueProp($state, [
            "sideBarNavigation",
            "currentPage"
          ])}
          onCurrentPageChange2={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, [
              "sideBarNavigation",
              "currentPage"
            ]).apply(null, eventArgs);

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
        />

        <div
          data-plasmic-name={"pageContent"}
          data-plasmic-override={overrides.pageContent}
          className={classNames(projectcss.all, sty.pageContent)}
        >
          <section
            data-plasmic-name={"pageSection"}
            data-plasmic-override={overrides.pageSection}
            className={classNames(projectcss.all, sty.pageSection)}
          >
            <AntdBreadcrumb
              data-plasmic-name={"breadcrumb"}
              data-plasmic-override={overrides.breadcrumb}
              className={classNames("__wab_instance", sty.breadcrumb)}
              itemsRaw={
                <React.Fragment>
                  <AntdBreadcrumbItem
                    className={classNames(
                      "__wab_instance",
                      sty.breadcrumbItem___9X7Ib
                    )}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__irWs3
                      )}
                    >
                      {"First"}
                    </div>
                  </AntdBreadcrumbItem>
                  <AntdBreadcrumbItem
                    className={classNames(
                      "__wab_instance",
                      sty.breadcrumbItem__vWsk
                    )}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pRJd1
                      )}
                    >
                      {"Second"}
                    </div>
                  </AntdBreadcrumbItem>
                  <AntdBreadcrumbItem
                    className={classNames(
                      "__wab_instance",
                      sty.breadcrumbItem__ouyrj
                    )}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eMylJ
                      )}
                    >
                      {"Third"}
                    </div>
                  </AntdBreadcrumbItem>
                </React.Fragment>
              }
              separator={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lda9X
                  )}
                >
                  {"/"}
                </div>
              }
            />

            {renderPlasmicSlot({
              defaultContents: (
                <section
                  className={classNames(projectcss.all, sty.section__pSdsE)}
                />
              ),

              value: args.children
            })}
          </section>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "freeBox",
    "sideBarNavigation",
    "pageContent",
    "pageSection",
    "breadcrumb"
  ],
  freeBox: [
    "freeBox",
    "sideBarNavigation",
    "pageContent",
    "pageSection",
    "breadcrumb"
  ],
  sideBarNavigation: ["sideBarNavigation"],
  pageContent: ["pageContent", "pageSection", "breadcrumb"],
  pageSection: ["pageSection", "breadcrumb"],
  breadcrumb: ["breadcrumb"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
  sideBarNavigation: typeof SideBarNavigation;
  pageContent: "div";
  pageSection: "section";
  breadcrumb: typeof AntdBreadcrumb;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMainPageLayout__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMainPageLayout__VariantsArgs;
    args?: PlasmicMainPageLayout__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicMainPageLayout__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicMainPageLayout__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMainPageLayout__ArgProps,
          internalVariantPropNames: PlasmicMainPageLayout__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMainPageLayout__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMainPageLayout";
  } else {
    func.displayName = `PlasmicMainPageLayout.${nodeName}`;
  }
  return func;
}

export const PlasmicMainPageLayout = Object.assign(
  // Top-level PlasmicMainPageLayout renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    sideBarNavigation: makeNodeComponent("sideBarNavigation"),
    pageContent: makeNodeComponent("pageContent"),
    pageSection: makeNodeComponent("pageSection"),
    breadcrumb: makeNodeComponent("breadcrumb"),

    // Metadata about props expected for PlasmicMainPageLayout
    internalVariantProps: PlasmicMainPageLayout__VariantProps,
    internalArgProps: PlasmicMainPageLayout__ArgProps
  }
);

export default PlasmicMainPageLayout;
/* prettier-ignore-end */
